services:
  solc-verify:
    image: solc-verify
    container_name: solc-verify-container
    volumes:
      - "../:/solc-verify-spec"
    working_dir: /solc-verify-spec
    stdin_open: true 
    tty: true         